name: daily-cron
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --url 'https://memesendertzali-production.up.railway.app/' 
