name: daily-cron
env:
  BOT_NUM: ${{secrets.BOT_NUM}}
  CHAT_NUM: ${{secrets.CHAT_NUM}}
  API_KEY: ${{secrets.API_KEY}}
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run : echo ${{secrets.API_KEY}} is API KEY
      - name: Run Script
        run: node index.js
        
