name: daily-cron
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'
      - run: npm install
      - name: Run Script
        run: node index.js
        env:
          BOT_NUM: ${{secrets.Prod.BOT_NUM}}
          CHAT_NUM: ${{secrets.Prod.CHAT_NUM}}
          API_KEY: ${{secrets.Prod.API_KEY}}

